# Reemplace estos valores por la configuración de su motor de base de datos.
# Ejemplo para MySQL: jdbc:mysql://localhost:3306/hospital_san_gabriel
# Se requiere agregar el driver JDBC correspondiente al proyecto.
db.url=jdbc:REEMPLAZAR_BASE_DE_DATOS://localhost:0000/hospital_san_gabriel
db.user=REEMPLAZAR_USUARIO
db.password=REEMPLAZAR_CONTRASENA
